### ISSUE TITLE
Download QRCode button doesn’t work 

### ISSUE THREAD

**Issue by theminer3746** [iammarkps/openhouse#1]
Environment:
iPad Pro 10.5” 
iOS 12 (latest)
Google Chrome (latest)

Steps to reproduce:
1. Fill all fields
2. Submit the form 
3. Try pressing the download qrcode button

**Comment by NamoDev** [comment]
This also does not work on Firefox 64.0 on Ubuntu 18.04

**Comment by iammarkps** [comment]
This issue is now fixed in https://github.com/iammarkps/openhouse/commit/c1c96d689cf90d3939b6ee8ac18f88013276f15d
